#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Display headers
printf "%-8s %-8s %-5s %-5s %-8s %-8s %-8s %-8s %-8s %s\n" \
  "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "COMMAND"

# Display process information using ps command
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest | tail -n +2
